project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests
    contractout: ctrout

networks:
    default: development
    development:
        host: https://127.0.0.1:8545
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        reverting_tx_gas_limit: max
        default_contract_owner: true
        chainid: 1337
        test_rpc:
            cmd: ganache-cli
            port: 8545
            gas_limit: 6721975
            accounts: 10
            mnemonic: brownie
    bsc-test:
        host: "https://data-seed-prebsc-1-s1.binance.org:8545/"
        explorer: https://testnet.bscscan.com/
    eth-mainnet:
      #gas_limit: 6721975
      #gas_price: 0
      host: https://mainnet.infura.io/v3/WEB3_INFURA_PROJECT_ID


    # bsc-main:
    #   host: "https://bsc-dataseed.binance.org"
    # #     gas_limit: max
    # #     gas_buffer: 1
    # #     gas_price: 0
    # #     reverting_tx_gas_limit: max
    # #     default_contract_owner: true

compiler:
    evm_version: null
    solc:
        version: 0.8.5
        optimizer:
            enabled: true
            runs: 200
        remappings: null
    vyper:
        version: null
